#!/bin/sh
# Regenerates z_cgo_link_{host,tinygo}.go with the MicroPython include paths
# for this checkout. Called from the justfile `embed` recipe.
#
# host.c (compiled by cgo, both targets) needs the MP embed include dirs, so
# the resolved absolute paths are baked into generated .go files rather than
# hard-coded. LDFLAGS point at the per-target MP archives built by the justfile.

set -e

ROOT="$(cd "$(dirname "$0")" && pwd)"
MP_ROOT="${1:?usage: gen_cgo.sh <MICROPYTHON_ROOT>}"
EMBED_DIR="$MP_ROOT/examples/embedding/micropython_embed"
CFLAGS="-I${EMBED_DIR} -I${EMBED_DIR}/port -I${EMBED_DIR}/.. -I${EMBED_DIR}/../.."

# Go's build cache keys cgo link actions on the generated file's CONTENT, not
# on the -l archive's bytes; without a fingerprint here, a rebuilt
# libmp_embed*.a would be silently linked against a stale cached archive.
HOST_FP="$(md5sum "$ROOT/build/libmp_embed_host.a" 2>/dev/null | cut -d' ' -f1)"
ARM_FP="$(md5sum "$ROOT/build/libmp_embed.a" 2>/dev/null | cut -d' ' -f1)"

cat > "$ROOT/z_cgo_link_host.go" <<EOF
//go:build !tinygo

// Code generated by cmd/embed/gen_cgo.sh; DO NOT EDIT.

package main

/*
#cgo CFLAGS: ${CFLAGS}
#cgo LDFLAGS: -Lbuild -lmp_embed_host -lm
// host archive fingerprint: ${HOST_FP}
*/
import "C"
EOF

cat > "$ROOT/z_cgo_link_tinygo.go" <<EOF
//go:build tinygo

// Code generated by cmd/embed/gen_cgo.sh; DO NOT EDIT.

package main

/*
#cgo CFLAGS: ${CFLAGS}
#cgo LDFLAGS: -Lbuild -lmp_embed
// arm archive fingerprint: ${ARM_FP}
*/
import "C"
EOF

echo "wrote $ROOT/z_cgo_link_host.go and $ROOT/z_cgo_link_tinygo.go"
