set(MICROPY_BOARD_DIR ${CMAKE_CURRENT_LIST_DIR})

set(PICO_BOARD ferretboard)
list(APPEND PICO_BOARD_HEADER_DIRS ${CMAKE_CURRENT_LIST_DIR})

set(MICROPY_HW_FLASH_STORAGE_BYTES 1441792)  # 1408 * 1024
set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest.py)