set(MICROPY_BOARD_DIR ${CMAKE_CURRENT_LIST_DIR})

set(PICO_BOARD ferretboard)
list(APPEND PICO_BOARD_HEADER_DIRS ${CMAKE_CURRENT_LIST_DIR})

set(MICROPY_HW_FLASH_STORAGE_BYTES 15728640)  # 15 * 1024 * 1024, leaves 1 MiB for firmware on 16 MB chip
set(MICROPY_FROZEN_MANIFEST ${MICROPY_BOARD_DIR}/manifest.py)